using Microsoft.AspNetCore.Http;
using Shoghlana.Core.Models;

namespace Shoghlana.Core.DTO
{
    public class FreelancerDTO
    {
        // I don't need ID in dto because it's auto generated by EF >> when send freelancer to front as dto , we want to send its id 
        public int Id { get; set; }

        //public string? PersonalImage { get; set; }

        public IFormFile? PersonalImageBytes { get; set; }

        public string Name { get; set; }

        public string Title { get; set; }

        public string? Address { get; set; }

        public string? Overview { get; set; }

        // should be uncommented and optional >> added on edit freelancer profile >> not added on freelancer creation >> use projectdto on adding , getprojectdto onretrieving

        public List<AddProjectDTO>? Portfolio { get; set; }

        public List<GetJobDTO>? WorkingHistory { get; set; }
        // TODO you cahnged it from DTO to GetDTO => not tested yet
        

        public List<ProposalDTO>? Proposals { get; set; }

        public List<SkillDTO>? skills { get; set; }

        //public List<Notification>? notifications { get; set; }
    }
}
